{{- if  .Values.metrics.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: stardog-metrics-collector-sh
  namespace: {{ include "stardog.namespace" . }}
  labels:
    helm.sh/chart: {{ include "stardog.chart" . }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: metrics
data:
  collector.sh: |
    #!/usr/bin/env sh

    nohup nginx &

    # mkdir -p /usr/share/nginx/stardog-metrics

    echo "Starting Stardog Server metrics collection on host $(hostname -f) at $(date) "
    while true; do
        curl -s -u admin:admin http://stardog-stardog.stardog.svc.cluster.local:5820/admin/status/prometheus > /usr/share/nginx/stardog-metrics/stardog-metrics.txt
        sleep 5;
    done
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stardog-metrics-nginx-conf
  namespace: {{ include "stardog.namespace" . }}
  labels:
    helm.sh/chart: {{ include "stardog.chart" . }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: metrics
data:
  nginx.conf: |
    error_log /tmp/error.log;

    # The pidfile will be written to /var/run unless this is set.
    pid /tmp/nginx.pid;

    worker_processes 1;

    events {
    worker_connections 1024;
    }
    http {
    # Set an array of temp and cache file options that will otherwise default to
    # restricted locations accessible only to root.
    client_body_temp_path /tmp/client_body;
    fastcgi_temp_path /tmp/fastcgi_temp;
    proxy_temp_path /tmp/proxy_temp;
    scgi_temp_path /tmp/scgi_temp;
    uwsgi_temp_path /tmp/uwsgi_temp;

    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    # include /etc/nginx/mime.types;
    index index.html index.htm index.php;

    default_type application/octet-stream;
      server {
        listen       9820;
        listen  [::]:9820;
        server_name  localhost;

        root /usr/share/nginx/stardog-metrics;
        location "/metrics" {
          try_files /stardog-metrics.txt =404;
        }

        location "/" {
          deny all;
        }

      }
    }
{{- end }}
