{{- if .Values.stardogLicense }}
apiVersion: v1
kind: Secret
metadata:
  name: stardog-license
  namespace: {{ include "stardog.namespace" . }}
data:
  stardog-license-key.bin: {{ .Values.stardogLicense }}
{{- end }}