{{- if and .Values.busybox.image.username .Values.busybox.image.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-image-busybox-pull-secret
  namespace: {{ include "stardog.namespace" . }}
  labels:
    helm.sh/chart: {{ include "stardog.chart" . }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecretBusybox" .  }}
{{- end }}
