{{- if (not .Values.admin.passwordSecretRef) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cachetarget.fullname" . }}-password
  namespace: {{ include "cachetarget.namespace" . }}
  labels:
    helm.sh/chart: {{ include "cachetarget.chart" . }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
data:
  password: {{ b64enc .Values.admin.password }}
{{- end }}