apiVersion: v1
kind: Service
metadata:
  name: {{ include "launchpad.fullname" . }}
  namespace: {{ include "launchpad.namespace" . }}
  labels:
    app: {{ include "launchpad.fullname" . }}
    helm.sh/chart: {{ include "launchpad.chart" . }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - name: http
    port: 8080
    targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  selector:
    app: {{ include "launchpad.fullname" . }}
