---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "voicebox.fullname" . }}
  namespace: {{ include "voicebox.namespace" . }}
  labels:
    helm.sh/chart: {{ include "voicebox.chart" . }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
data:
  vbx_config.json: {{ .Values.configFile | quote }}
