---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "voicebox.fullname" . }}
  namespace: {{ include "voicebox.namespace" . }}
  labels:
    app: {{ include "voicebox.fullname" . }}
    helm.sh/chart: {{ include "voicebox.chart" . }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  type: {{ .Values.service.type }}
  {{- if (ne .Values.service.loadBalancerIP "") }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  selector:
    app: {{ include "voicebox.fullname" . }}
